# Generated by Django 3.0.2 on 2020-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200422_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], default='', max_length=10, null='true'),
        ),
    ]
