# Generated by Django 3.0.2 on 2020-04-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200422_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, null='true'),
        ),
    ]
