# Generated by Django 3.0.3 on 2020-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200430_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='', max_length=10, null='true'),
        ),
    ]
