# Generated by Django 2.2 on 2020-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200430_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, null='true'),
        ),
    ]
