# Generated by Django 3.0.3 on 2020-05-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200503_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], default='', max_length=10, null='true'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='to_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
