# Generated by Django 3.0.3 on 2020-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200503_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, null='true'),
        ),
    ]
