# Generated by Django 3.0.3 on 2020-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200503_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], default='', max_length=10, null='true'),
        ),
    ]
