# Generated by Django 3.0.3 on 2020-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200504_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], default='', max_length=10, null='true'),
        ),
    ]
