# Generated by Django 3.0.3 on 2020-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200504_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='true', choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], default='', max_length=10, null='true'),
        ),
    ]
