# Generated by Django 3.0.3 on 2020-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cook_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='difficulty',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='prep_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='servings',
            field=models.CharField(default='', max_length=30),
        ),
    ]
