# Generated by Django 3.0.3 on 2020-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200407_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='steps_to_follow',
            field=models.CharField(default='', max_length=500),
        ),
    ]
