# Generated by Django 3.0.3 on 2020-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_food_steps_to_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.CharField(default='', max_length=100),
        ),
    ]
