# Generated by Django 3.0.3 on 2020-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200410_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='steps_to_follow',
            field=models.TextField(default=''),
        ),
    ]
