# Generated by Django 3.0.3 on 2020-04-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200410_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
    ]
