# Generated by Django 3.0.3 on 2020-04-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200411_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
