# Generated by Django 3.0.3 on 2020-04-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200411_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='author',
        ),
    ]
