# Generated by Django 3.0.3 on 2020-04-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_food_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
    ]
