# Generated by Django 3.0.3 on 2020-04-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200411_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='author',
        ),
    ]
