# Generated by Django 3.0.3 on 2020-04-11 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0022_food_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='chef',
        ),
        migrations.AddField(
            model_name='food',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
