# Generated by Django 3.0.3 on 2020-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20200411_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='', max_length=30),
        ),
    ]
