# Generated by Django 3.0.3 on 2020-04-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200413_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Non veg', 'Non veg'), ('Veg', 'Veg'), ('North Indian', 'North Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('American', 'American')], default='', max_length=30),
        ),
    ]
