# Generated by Django 3.0.3 on 2020-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20200413_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(default='', to='myapp.Category'),
        ),
    ]
