# Generated by Django 3.0.2 on 2020-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200418_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank='true', null='true'),
            preserve_default='true',
        ),
    ]
