# Generated by Django 3.0.2 on 2020-04-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20200422_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
