# Generated by Django 3.0.2 on 2020-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_comment_comment_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author_email',
            field=models.EmailField(default='Anonymous', max_length=254),
        ),
    ]
