# Generated by Django 3.0.3 on 2020-05-02 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20200430_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
