# Generated by Django 3.0.3 on 2020-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_food_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
