# Generated by Django 3.0.3 on 2020-05-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='visit_count',
            new_name='visit',
        ),
    ]
